In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import seaborn as sns
data_electronic = pd.read_csv('用電量.csv')
data_electronic.head()

In [64]:
data_price = pd.read_csv('price.csv')
data_price['日期'] = data_price['日期'].astype(str)
data_price

          日期  每度平均售價(元)
0   201901.0       2.44
1   201902.0       2.39
2   201903.0       2.40
3   201904.0       2.42
4   201905.0       2.42
5   201906.0       2.70
6   201907.0       2.88
7   201908.0       2.95
8   201909.0       2.98
9   201910.0       2.63
10  201911.0       2.51
11  201912.0       2.51
12  202001.0       2.36
13  202002.0       2.42
14  202003.0       2.42
15  202004.0       2.38
16  202005.0       2.33
17  202006.0       2.71
18  202007.0       2.87
19  202008.0       2.70
20  202009.0       2.75
21  202010.0       2.53
22  202011.0       2.43
23  202012.0       3.13
24  202101.0       2.37
25  202102.0       2.40
26  202103.0       2.42
27  202104.0       2.44
28  202105.0       2.39
29  202106.0       2.74
30  202107.0       2.86
31  202108.0       2.56
32  202109.0       2.91
33  202110.0       2.71
34  202111.0       2.57
35  202112.0       2.55
36  202201.0       2.37
37  202202.0       2.39
38  202203.0       2.42
39  202204.0       2.38
40  202205.0       2.39
41  202206.0       2.71
42  202207.0       3.03
43  202208.0       3.20
44  202209.0       3.24
45  202210.0       2.78
46  202211.0       2.75
47  202212.0       2.73
48       nan        NaN
49       nan        NaN
50       nan        NaN

In [47]:
df1 = data_electronic.loc[data_electronic.縣市 == '台北市']
#df1['日期'] = pd.to_datetime(df1["日期"], format="%y%m")
df1['日期'] = df1['日期'].astype(str)
year_column = pd.Series([])
month_column = pd.Series([])
df1['年份'] = new_column
df1['月份'] = new_column
df1['年份'] = df1['日期'].str[:4].astype(int)
df1['月份'] = df1['日期'].str[4:7].astype(int)
print(df1)

'''
df2 = data_electronic.loc[data_electronic.縣市 == '新北市']
df3 = data_electronic.loc[data_electronic.縣市 == '桃園市']
df4 = data_electronic.loc[data_electronic.縣市 == '台中市']
df5 = data_electronic.loc[data_electronic.縣市 == '台南市']
df6 = data_electronic.loc[data_electronic.縣市 == '高雄市']
'''

          日期   縣市  住宅部門售電量(度)  住宅部門用電佔比(%)  服務業部門(含包燈)(度)  服務業部門(含包燈)用電佔比(%)  \
1     202212  台北市   343386529       0.3157      696782918             0.6407
24    202211  台北市   447027336       0.3491      775222779             0.6054
47    202210  台北市   574270630       0.3948      824666263             0.5669
70    202209  台北市   697546339       0.4064      948828222             0.5529
93    202208  台北市   577847950       0.3682      931998553             0.5939
116   202207  台北市   497087589       0.3375      911711730             0.6191
139   202206  台北市   376948142       0.3117      781452425             0.6463
162   202205  台北市   342630235       0.3061      725692045             0.6483
185   202204  台北市   340813727       0.3277      657762441             0.6325
208   202203  台北市   421676141       0.3561      710780186             0.6002
231   202202  台北市   384018580       0.3774      593192874             0.5830
254   202201  台北市   376095933       0.3384      682419561             0.6141
277   202112  台北市   386895893       0.3412      698906684             0.6164
300   202111  台北市   539006246       0.3947      765780475             0.5607
323   202110  台北市   611087438       0.4046      842796300             0.5580
346   202109  台北市   656940979       0.4080      886802200             0.5507
369   202108  台北市   631540380       0.4242      801852205             0.5386
392   202107  台北市   609381213       0.4155      793483846             0.5410
415   202106  台北市   470480803       0.3796      719859856             0.5808
438   202105  台北市   390590617       0.3183      779813023             0.6355
461   202104  台北市   366850355       0.3357      681155892             0.6234
484   202103  台北市   412836083       0.3529      705060039             0.6027
507   202102  台北市   390393905       0.3845      585301517             0.5764
530   202101  台北市   399211598       0.3561      668672895             0.5964
553   202012  台北市   332428173       0.3118      686693876             0.6440
576   202011  台北市   442744676       0.3509      760965594             0.6031
599   202010  台北市   564603228       0.3985      798862688             0.5638
622   202009  台北市   680800675       0.4030      940229635             0.5565
645   202008  台北市   647375629       0.4027      902405551             0.5614
668   202007  台北市   616958564       0.3725      969311390             0.5852
691   202006  台北市   462474398       0.3423      836254965             0.6189
714   202005  台北市   398132374       0.3253      769519607             0.6287
737   202004  台北市   357907072       0.3424      643542166             0.6156
760   202003  台北市   395854023       0.3526      675198143             0.6015
783   202002  台北市   374776025       0.3568      632389689             0.6020
806   202001  台北市   350787555       0.3296      663459897             0.6233
829   201912  台北市   357165678       0.3251      695036102             0.6327
852   201911  台北市   445803367       0.3475      776055452             0.6049
875   201910  台北市   542987457       0.3737      850268021             0.5851
898   201909  台北市   664694423       0.3945      947489293             0.5623
921   201908  台北市   570733303       0.3589      955957404             0.6011
944   201907  台北市   496899546       0.3285      946659596             0.6258
967   201906  台北市   406626583       0.3096      851099023             0.6479
990   201905  台北市   383138279       0.3008      828124754             0.6501
1013  201904  台北市   334554739       0.3021      722818693             0.6527
1036  201903  台北市   353535732       0.3206      695577522             0.6308
1059  201902  台北市   338095776       0.3392      615405369             0.6174
1082  201901  台北市   358179967       0.3166      714973678             0.6320

      農林漁牧售電量(度)  農林漁牧用電佔比(%)  工業部門售電量(度)  工業部門用電佔比(%)    合計售電量(度)  縣市用電佔比(%)  \
1         435330       0.0004    46940814       0.0432  1087545591     0.0615
24        429596       0.0003    57821099       0.0452  1280500810     0.0670
47        462471       0.0003    55302768       0.0380  1454702132     0.0697
70        490202       0.0003    69375448       0.0404  1716240211     0.0775
93        497666       0.0003    58990459       0.0376  1569334628     0.0745
116       626358       0.0004    63221336       0.0429  1472647013     0.0699
139      1212657       0.0010    49576271       0.0410  1209189495     0.0629
162      1157519       0.0010    49849497       0.0445  1119329296     0.0603
185       892359       0.0009    40413915       0.0389  1039882442     0.0585
208       966413       0.0008    50780815       0.0429  1184203555     0.0626
231       807268       0.0008    39479919       0.0388  1017498641     0.0616
254       970128       0.0009    51746568       0.0466  1111232190     0.0623
277      1001153       0.0009    47077465       0.0415  1133881195     0.0610
300      1013171       0.0007    59956329       0.0439  1365756221     0.0682
323      1251204       0.0008    55351740       0.0366  1510486682     0.0703
346      1291042       0.0008    65177321       0.0405  1610211542     0.0752
369      1292092       0.0009    54077565       0.0363  1488762242     0.0706
392      1264440       0.0009    62567810       0.0427  1466697309     0.0700
415      1219839       0.0010    47900634       0.0386  1239461132     0.0636
438      1219460       0.0010    55369370       0.0451  1226992470     0.0645
461      1042891       0.0010    43635209       0.0399  1092684347     0.0616
484      1218779       0.0010    50786075       0.0434  1169900976     0.0639
507      1035621       0.0010    38714278       0.0381  1015445321     0.0648
530      1129074       0.0010    52177065       0.0465  1121190632     0.0649
553      1228614       0.0012    45965846       0.0431  1066316509     0.0615
576      1268769       0.0010    56708208       0.0449  1261687247     0.0684
599      1395216       0.0010    52035417       0.0367  1416896549     0.0712
622      1535698       0.0009    66970873       0.0396  1689536881     0.0801
645      1667674       0.0010    56092474       0.0349  1607541328     0.0772
668      1672812       0.0010    68369910       0.0413  1656312676     0.0793
691      1536386       0.0011    50843223       0.0376  1351108972     0.0727
714      1439011       0.0012    54888987       0.0448  1223979979     0.0695
737      1120700       0.0011    42736484       0.0409  1045306422     0.0637
760      1162382       0.0010    50381133       0.0449  1122595681     0.0653
783      1075740       0.0010    42193358       0.0402  1050434812     0.0649
806      1158389       0.0011    48979335       0.0460  1064385176     0.0677
829      1213291       0.0011    45156930       0.0411  1098572001     0.0653
852      1305001       0.0010    59707618       0.0465  1282871438     0.0716
875      1486284       0.0010    58402821       0.0402  1453144583     0.0753
898       684856       0.0004    72143110       0.0428  1685011682     0.0839
921       755008       0.0005    62995463       0.0396  1590441178     0.0791
944       724884       0.0005    68404624       0.0452  1512688650     0.0777
967       664876       0.0005    55141444       0.0420  1313531926     0.0730
990       642721       0.0005    61966031       0.0486  1273871785     0.0708
1013      539708       0.0005    49588433       0.0448  1107501573     0.0665
1036      542609       0.0005    52969004       0.0480  1102624867     0.0665
1059      465516       0.0005    42855962       0.0430   996822623     0.0684
1082      543048       0.0005    57513110       0.0508  1131209803     0.0682

        年份  月份
1     2022  12
24    2022  11
47    2022  10
70    2022   9
93    2022   8
116   2022   7
139   2022   6
162   2022   5
185   2022   4
208   2022   3
231   2022   2
254   2022   1
277   2021  12
300   2021  11
323   2021  10
346   2021   9
369   2021   8
392   2021   7
415   2021   6
438   2021   5
461   2021   4
484   2021   3
507   2021   2
530   2021   1
553   2020  12
576   2020  11
599   2020  10
622   2020   9
645   2020   8
668   2020   7
691   2020   6
714   2020   5
737   2020   4
760   2020   3
783   2020   2
806   2020   1
829   2019  12
852   2019  11
875   2019  10
898   2019   9
921   2019   8
944   2019   7
967   2019   6
990   2019   5
1013  2019   4
1036  2019   3
1059  2019   2
1082  2019   1

C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['日期'] = df1['日期'].astype(str)
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  year_column = pd.Series([])
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:5: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  month_column = pd.Series([])
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:6: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  date_column = pd.Series([])
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['年份'] = new_column
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['月份'] = new_column
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['年份'] = df1['日期'].str[:4].astype(int)
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\1567309372.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['月份'] = df1['日期'].str[4:7].astype(int)

"\ndf2 = data_electronic.loc[data_electronic.縣市 == '新北市']\ndf3 = data_electronic.loc[data_electronic.縣市 == '桃園市']\ndf4 = data_electronic.loc[data_electronic.縣市 == '台中市']\ndf5 = data_electronic.loc[data_electronic.縣市 == '台南市']\ndf6 = data_electronic.loc[data_electronic.縣市 == '高雄市']\n"

In [60]:
df2 = data_price
df2['日期'] = df2['日期'].astype(str)
year_column2 = pd.Series([])
month_column2 = pd.Series([])
df2['年份'] = new_column
df2['月份'] = new_column
df2['年份'] = df2['日期'].str[:4].astype(str)
df2['月份'] = df2['日期'].str[4:6].astype(str)
print(df2)

          日期  每度平均售價(元)    年份  月份
0   201901.0       2.44  2019  01
1   201902.0       2.39  2019  02
2   201903.0       2.40  2019  03
3   201904.0       2.42  2019  04
4   201905.0       2.42  2019  05
5   201906.0       2.70  2019  06
6   201907.0       2.88  2019  07
7   201908.0       2.95  2019  08
8   201909.0       2.98  2019  09
9   201910.0       2.63  2019  10
10  201911.0       2.51  2019  11
11  201912.0       2.51  2019  12
12  202001.0       2.36  2020  01
13  202002.0       2.42  2020  02
14  202003.0       2.42  2020  03
15  202004.0       2.38  2020  04
16  202005.0       2.33  2020  05
17  202006.0       2.71  2020  06
18  202007.0       2.87  2020  07
19  202008.0       2.70  2020  08
20  202009.0       2.75  2020  09
21  202010.0       2.53  2020  10
22  202011.0       2.43  2020  11
23  202012.0       3.13  2020  12
24  202101.0       2.37  2021  01
25  202102.0       2.40  2021  02
26  202103.0       2.42  2021  03
27  202104.0       2.44  2021  04
28  202105.0       2.39  2021  05
29  202106.0       2.74  2021  06
30  202107.0       2.86  2021  07
31  202108.0       2.56  2021  08
32  202109.0       2.91  2021  09
33  202110.0       2.71  2021  10
34  202111.0       2.57  2021  11
35  202112.0       2.55  2021  12
36  202201.0       2.37  2022  01
37  202202.0       2.39  2022  02
38  202203.0       2.42  2022  03
39  202204.0       2.38  2022  04
40  202205.0       2.39  2022  05
41  202206.0       2.71  2022  06
42  202207.0       3.03  2022  07
43  202208.0       3.20  2022  08
44  202209.0       3.24  2022  09
45  202210.0       2.78  2022  10
46  202211.0       2.75  2022  11
47  202212.0       2.73  2022  12
48       nan        NaN   nan
49       nan        NaN   nan
50       nan        NaN   nan

C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\2708431352.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  year_column2 = pd.Series([])
C:\Users\kungc\AppData\Local\Temp\ipykernel_9688\2708431352.py:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  month_column2 = pd.Series([])

In [ ]:
data_electronic_new=pd.concat([df1,df2,df3,df4,df5,df6],axis=0)#合併
data_electronic_new

In [ ]:
data_price = pd.read_csv('price.csv')
data_price

In [ ]:
data_electronic_merge = pd.merge(data_electronic_new,data_price,on = '日期')
data_electronic_merge